# Assignment:
When, x = height and y = weight
Create a ML model which will predict weight based on height. 

In [1]:
import pandas as pd #import pandas method and rename as pd for using easily in future in this program. 
import numpy as np #import numpy method and rename as np for using easily in future in this program. 
import matplotlib.pyplot as plt #import pyplot which is under matplotlib and renamed as plt for easily use in future in programe. 

In [2]:
df = pd.read_excel("Height-Weight Data.xlsx") # read the Excel file frm the current directory

In [3]:
x = df[['Height']]
y = df['Weight']

In [4]:
from sklearn.model_selection import train_test_split # X (Height) and Y (Weight) are given. We will split the given datasheet for training 

In [5]:
xtrain,xtest, ytrain,ytest = train_test_split(x,y, test_size = .30) # trainning data = 70%

# Model Creation

In [6]:
from sklearn.linear_model import LinearRegression #import LinearRegression frm sklearn.linear_model

In [7]:
reg = LinearRegression() # creat a n object 'reg'

In [8]:
reg.fit(xtrain, ytrain) #Training ML Model

LinearRegression()

In [9]:
m = reg.coef_ #Co-efficient

In [10]:
c = reg.intercept_ #Intercept

In [11]:
x1 = 71.730978

In [12]:
y = (m*x1)+c

In [13]:
y

array([203.10499633])

In [14]:
reg.predict([[71.730978]]) # we get the same results from the commend reg.predict commend and y=(m*x)+c formula

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([203.10499633])

In [15]:
df['predicted result'] = reg.predict(x) # Here df['predicted result'] is the corrosponding value of y for x

In [16]:
df

Height      Weight  predicted result
0     73.847017  241.893563        215.690450
1     68.781904  162.310473        185.564945
2     74.110105  212.740856        217.255206
3     71.730978  220.042470        203.104999
4     69.881796  206.349801        192.106714
...         ...         ...               ...
3496  69.296830  185.649086        188.627543
3497  70.542201  210.198845        196.034573
3498  73.912549  202.429960        216.080212
3499  67.396021  144.277671        177.322201
3500  72.738970  187.222909        209.100177

[3501 rows x 3 columns]

In [17]:
pred = reg.predict(xtest) # pred is the Corrosponding results of ytest

In [18]:
pred

array([197.12035503, 157.87146664, 144.78575518, ..., 202.29495642,
       176.66454344, 180.87873936])

In [19]:
from sklearn.metrics import mean_squared_error #Error check for the constructed ML model

In [20]:
mse = mean_squared_error(ytest, pred)

In [21]:
mse

98.61607394279827

In [22]:
from sklearn.metrics import mean_absolute_error 

In [23]:
mae = mean_absolute_error(ytest, pred) #mae is always smaller than mse

In [24]:
mae

7.938265080763474